### ISSUE TITLE
gistcdn.githack.com JS files are not optimized

### ISSUE THREAD

**Issue by XhmikosR** [uniibu/lebab-ce#16]

**Comment by uniibu** [comment]
fixed by commit https://github.com/uniibu/lebab-ce/commit/4bcb1a0f535e13edf40d54d159ed33792a432a43 Thanks!

**Comment by XhmikosR** [comment]
@uniibu: those aren't not minified either :/

Why do you need to target the latest lebab like that? IMO you just use it through package.json.

**Comment by XhmikosR** [comment]
Ah, wait it is, it just has line breaks. All good then :)

**Comment by XhmikosR** [comment]
@uniibu I'm still seeing unminified files from https://cdn.staticaly.com/, see https://gtmetrix.com/reports/lebab.unibtc.me/X1M96fyG
